apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ci-agent
  namespace: jenkins
  labels:
    app: jenkins-ci-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ci-agent
  template:
    metadata:
      labels:
        app: jenkins-ci-agent
    spec:
      containers:
        - name: jenkins-ci-agent
          image: alexohneander/jenkins-ci-agent:latest
          ports:
            - containerPort: 2376
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ci-agent
  namespace: jenkins
spec:
  selector:
    app: jenkins-ci-agent
  ports:
    - protocol: TCP
      port: 2376
      targetPort: 2376
